### ISSUE TITLE
Pose6D.h issue when catkin_make

### ISSUE THREAD

**Issue by LperryL** [SiyuanHuang95/Livox-Localization#8]
When I catkin_make the project, there is an error happen:
fatal error:fast_lio/Pose6D.h: No such file or directory
#include <fast_lio/Pose6D.h>
compilation terminated

I have successfully build and run fast_lio, but it still output this error, have someone met or fixed this problem?

**Comment by SiyuanHuang95** [comment]
It's due to the generation of the message issue, just run catkin_make more times...

**Comment by valenbase** [comment]
> It's due to the generation of the message issue, just run catkin_make more times...

Maybe the real reason is that the package's name is livox_localization but not fast_lio, so ros can't find fast_lio/Pose6D.h

**Comment by SiyuanHuang95** [comment]
Cool. I haven’t noticed that before!Thanks for your insight!在 2022年10月6日，14:54，heiheihei ***@***.***> 写道：﻿

It's due to the generation of the message issue, just run catkin_make more times...

Maybe the real reason is that the package's name is livox_localization but not fast_lio, so ros can't find fast_lio/Pose6D.h
