### ISSUE TITLE
MID-70 available

### ISSUE THREAD

**Issue by Minsu-Kim1822** [SiyuanHuang95/Livox-Localization#9]
Hi, 
Does this package is available for MID-70??

**Comment by SiyuanHuang95** [comment]
If you just need to apply this repo for one new sensor setting, I would suggest that you might need to check out the differences between Mid-70 and Horizon first. Since we do not have Mid-70 available, no detailed help could be offered.

The main difference would occur in the feature extraction. The backend is almost the same.
